# Profile: PROD ? deploy server
# ??c t? environment variable
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.taskmanagement=INFO
logging.level.org.hibernate.SQL=WARN

# T?t Swagger trong prod
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false